# Generated by Django 5.2.11 on 2026-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("total_entries", models.IntegerField(default=0)),
                ("new_entries", models.IntegerField(default=0)),
                ("avg_words_learned", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Günlük İstatistik",
                "verbose_name_plural": "Günlük İstatistikler",
                "ordering": ["-date"],
            },
        ),
    ]
